In [1]:
import numpy as np
import pandas as pd

In [11]:
def new_board(size = (3,3)):
    State = np.empty(size, dtype=np.float16)
    State[:,:] = np.nan
    return State

In [20]:
def make_rand_move(arr, value):
    if not np.isnan(arr).any():
        print('No moves avaible')
        return 1
    else:
        while True:
            x = np.random.randint(3)
            y = np.random.randint(3)
            if np.isnan(arr[y,x]):
                break
        arr[y,x] = np.float16(value)
        return 0

In [16]:
def is_win(arr, value):
    horizontally = np.all(arr == value, axis=1)
    vertically = np.all(arr == value, axis=0)
    diagon_1 = np.all(arr[(0,1,2), (0,1,2)] == value)
    diagon_2 = np.all(arr[(0,1,2), (2,1,0)].all == value)
    if True in (horizontally.any(),
                vertically.any(),
                diagon_1,
                diagon_2):
        return True
    else:
        return False

In [7]:
def r(arr, who_am_I):
    oponent = np.abs(who_am_I - 1)
    if is_win(arr, who_am_I):
        return 1
    if is_win(arr, oponent):
        return 0
    else:
        return 0.5

In [69]:
def show_state_wrapper(func_name):
    def inner_func(who_am_I):
        print(r(State, 1))
        return func_name(who_am_I)
    return inner_func

@show_state_wrapper
def play(who_am_I):
    oponent = np.abs(who_am_I - 1)
    State = new_board()
    while True:
        if make_rand_move(State, who_am_I):
            break
        if make_rand_move(State, oponent):
            break
        yield State

In [21]:
State = new_board()
for i in range(5):
    make_rand_move(State, 1)
    make_rand_move(State, 0)
    print(r(State, 1))
    print(State, end='\n\n')

0.5
[[ 1. nan nan]
 [nan  0. nan]
 [nan nan nan]]

0.5
[[ 1.  0.  1.]
 [nan  0. nan]
 [nan nan nan]]

0.5
[[ 1.  0.  1.]
 [nan  0. nan]
 [ 0.  1. nan]]

0.5
[[ 1.  0.  1.]
 [nan  0.  1.]
 [ 0.  1.  0.]]

No moves avaible
0.5
[[1. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]]



In [14]:
make_rand_move(State, 1)

In [50]:
temp = State[(0,1,2), (0,1,0)] == 1
temp2 = temp[:2]
temp2
if True in (temp.any(), temp2.any()):
    print(temp)

[ True False False]


In [32]:
State[(2), (0,2)]

array([1., 1.], dtype=float16)

In [74]:
np.all(State == 1, axis=0)

array([False, False, False])

In [12]:
new_board()

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]], dtype=float16)

In [70]:
p = play(1)

0.5


In [76]:
print(next(p))

StopIteration: 

In [43]:
def temp(number):
    while True:
        number += 1
        yield number
        if number==10:
            break

In [48]:
t = temp(3)

In [53]:
next(t)

7